# Site settings
title: Sreenidhi Hub
email: 
description: >
    Get involved with the Campus initiatives at Mozilla
baseurl: "/innovationhub"
url: "https://starksources.github.io/innovationhub"
twitter_username: mozparticipate
github_username:  mozilla

# Build settings
markdown: kramdown

include: ['_pages']
