# Site settings
title: Sreenidhi Hub
email: 
description: >
    Get involved with the Campus initiatives at Mozilla
baseurl: ""
url: "https://snistinnovationhub.github.io/"
twitter_username: snist
github_username:  snistinnovationhub

# Build settings
markdown: kramdown

include: ['_pages']
