# Site settings
title: Sreenidhi Hub
email: sreenidhihub@sreenidhi.edu.in
description: >
    Get involved with the Innovative initiatives at SNIST
baseurl: ""
url: "https://snistinnovationhub.github.io/"
twitter_username: snist
github_username:  snistinnovationhub

# Build settings
markdown: kramdown

include: ['_pages']
